### ISSUE TITLE
CodeGenerator.AsyncLambda does not contain overload with result variable

### ISSUE THREAD

**Issue by scharnyw** [sakno/dotNext#13]
According to the [docs](https://sakno.github.io/dotNext/features/metaprogramming/async.html#async-lambda) on Async Lambda:

> `AsyncLambda` factory method is overloaded by two versions of this method:
    `AsyncLambda((fun, result) => { })` introduces special variable `result` that can be used to assign result of the function. This approach is similar to Result variable in Pascal programming language.
    `AsyncLambda(fun => { })` doesn't introduce special variable for the function result and control transfer to the caller is provided by `CodeGenerator.Return` method.

However, it appears that the first overload (the one with `result`) does not exist in the source code. The only overload I can find is the second one [here](https://github.com/sakno/dotNext/blob/1f593c9cee3743d7b30bed054bfd0ef9e4eb532e/src/DotNext.Metaprogramming/Metaprogramming/CodeGenerator.cs#L1242). It appears that to return values from an `AsyncLambda`, one needs to explicitly call `CodeGenerator.Return` instead.

Perhaps the discrepancy is because the overload with `result` is yet to be implemented?

**Comment by sakno** [comment]
@scharnyw , this overload exists for regular lambda expression builder, but not for async lambda builder. I'll check why this was removed. If it was by accident then I will return it in the next version of the library.

**Comment by sakno** [comment]
Release `DotNext.Metaprogramming 2.11.0` is published on NuGet.
