### ISSUE TITLE
Exceptions thrown in async lambda seem to be supressed

### ISSUE THREAD

**Issue by Skyppid** [sakno/dotNext#14]
I had to do quite a bit of work to get my code running, but so far it does generate perfectly well working asynchronous methods for my automatic serialization of entities. But while there is no compilation error and it does execute like expected, I realized that exceptions that are thrown inside the generated delegate don't propagate. I catch an exception in the async method I call via the AsyncLambda and rethrow it so it bubbles up my pipeline. But it never reaches the code calling the "AsyncLambda". It seems like the exception just get lost and execution stops. This is a serious issue as I can't recover from this state and don't get feedback when any exception occurs.

If this is a known problem, I'd like to hear if there's any progress to fixing that. If you need an example or more thorough explanation I'd give that preferrably in private.

**Comment by sakno** [comment]
@Skyppid could you please try the latest build from `develop` branch?

**Comment by Skyppid** [comment]
Will do so tomorrow when I'm in the office. Thanks for the quick reaction!

**Comment by Skyppid** [comment]
Can confirm, they're now properly propagated. Thanks for the quick fix!
