### ISSUE TITLE
An attempt was made to transition a task to a final state when it had already completed

### ISSUE THREAD

**Issue by Skyppid** [sakno/dotNext#15]
Partially related to my other issue (#14), when I fixed the issue in my code the state machine seems to become invalid at some point (I guess the return might not be valid). I get this exception + stack trace:

>    at void DotNext.Runtime.CompilerServices.AsyncStateMachine<TState, TResult>.System.Runtime.CompilerServices.IAsyncStateMachine.MoveNext() in /_/src/DotNext.Metaprogramming/Runtime/CompilerServices/AsyncStateMachine.cs:line 380
>    at void System.Runtime.CompilerServices.AsyncTaskMethodBuilder<TResult>+AsyncStateMachineBox<TStateMachine>.MoveNext(Thread threadPoolThread)
>    at Action System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents(Task task, Action continuation)+(Action innerContinuation, Task innerTask) => { }
>    at void System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, object state, ref Task currentTask)
>    at void System.Threading.Tasks.Task.ThrowAsync(Exception exception, SynchronizationContext targetContext)+(object state) => { }
>    at void System.Threading.QueueUserWorkItemCallback.s_executionContextShim(QueueUserWorkItemCallback quwi)
>    at void System.Threading.QueueUserWorkItemCallback.Execute()
>    at bool System.Threading.ThreadPoolWorkQueue.Dispatch()

This is my code for generating the lambda:
```
var funcSignature = typeof(Func<,,,>).MakeGenericType(writerType, typeof(EntityBase),
    typeof(CancellationToken), typeof(Task<>).MakeGenericType(typeof(byte[])));

var method = typeof(CodeGenerator).GetMethod(nameof(CodeGenerator.AsyncLambda))
    .MakeGenericMethod(funcSignature).Unreflect();
var compileMethod = typeof(Expression<>).MakeGenericType(funcSignature)
    .GetMethod(nameof(LambdaExpression.Compile), BindingFlags.Public | BindingFlags.Instance, null,
        CallingConventions.Any, Type.EmptyTypes, null).Unreflect();

finalExpression = method(null, (Action<LambdaContext>)GenerateAsyncLambda);
finalExpression = compileMethod(finalExpression);

void GenerateAsyncLambda(LambdaContext c)
{
    var localWriter = DeclareVariable("writer", c[0]);
    var localEntity = DeclareVariable("e", c[1]);
    var localToken = DeclareVariable("token", c[2]);

    var actualEntity = DeclareVariable(entityType, "actualEntity");
    Assign(actualEntity, Expression.Convert(localEntity, entityType));
    
    ParameterReplacer replacer = new ParameterReplacer(localWriter, actualEntity, localToken, entityType);
    foreach (var expr in writerExpressions)
        Await(replacer.Visit(expr), true);
}
```

EDIT: I tried adding `Return()` at the end, but that's not working either.

**Comment by sakno** [comment]
@Skyppid what kind of exception has been thrown? I don't see it in stack trace

**Comment by Skyppid** [comment]
Oh sorry, it was an InvalidOperationException. Wait I'll give you a more thorough stack trace as I compiled it myself meanwhile and ran it with symbols.

>An attempt was made to transition a task to a final state when it had already completed.

>    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource) in /_/src/System.Private.CoreLib/shared/System/ThrowHelper.cs:line 229
>    at DotNext.Runtime.CompilerServices.AsyncStateMachine`2.System.Runtime.CompilerServices.IAsyncStateMachine.MoveNext() in E:\External\dotNext\src\DotNext.Metaprogramming\Runtime\CompilerServices\AsyncStateMachine.cs:line 380
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs:line 201
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/System.Private.CoreLib/shared/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 63
>    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 654
>    at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 310
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs:line 201
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/System.Private.CoreLib/shared/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 63
>    at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/TaskContinuation.cs:line 701
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/System.Private.CoreLib/shared/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 63
>    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 1954
>    at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi) in /_/src/System.Private.CoreLib/shared/System/Threading/ThreadPool.cs:line 808
>    at System.Threading.QueueUserWorkItemCallback.Execute() in /_/src/System.Private.CoreLib/shared/System/Threading/ThreadPool.cs:line 824
>    at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/System.Private.CoreLib/shared/System/Threading/ThreadPool.cs:line 699

**Comment by sakno** [comment]
@Skyppid , you trying to build async lambda with non-void return type (of `Task<byte[]>`). However, `GenerateAsyncLambda` doesn't return anything. In this case, code generator will generate `return null` statement by default. Probably, the exception caused by generated code, not by Metaprogramming layer itself.

**Comment by sakno** [comment]
Could you please provide small repro code for that?

**Comment by Skyppid** [comment]
Well, I might have mixed things up. It's a rather complex construct where I call several async methods inside the generated async lambda, you're definetly right with the invalid return value. I'll check this when I'm in the office tomorrow and report back if it fixed the issue. If not, I'll give you some repro code sample to check it out.

**Comment by Skyppid** [comment]
Okay, you were right. I mixed things up - obviously it has to be `Func<,,,Task>`. The `Func<byte[]>` was from the generated expressions which are awaited inside that async lambda construct. Thanks!

**Comment by Skyppid** [comment]
Okay, the issue isn't resolved. I thought it was but it turned out my exception flow (early prototype) and logging is insufficient and invalid at that point and it actually just supressed the exception that initially the `AsyncLambda` signature is an ambigiuous match (#13). Then I had a version mismatch since the NuGet reference overwrote the base DotNext library referenced with an older version.

So in the end it's not the return value. You were right, that this method should return Task only without any actual return value since it's an asynchronous method, but yet I still get this very exception all the time. I'll prepare a little sample project.

**Comment by sakno** [comment]
Waiting for the update. All opened issues are fixed and I'm ready to prepare a new release.

**Comment by Skyppid** [comment]
I realized the difference between my sample and the actual application but even when I changed it to the very same implementation I can't reproduce the issue. What I found out though is that this seems to be a threading issue which I now doubt to be originating from within DotNext. When I await my parallel tasks instead of spawning them and letting it all work concurrently, it does not throw any exception and run a thousand times faster at that.

I can still show you the example if you want, but I guess you would be better off just releasing the new version with current fixes and ignore this issue.

**Comment by sakno** [comment]
@Skyppid make sure that you really need to generate async lambda dynamically via metaprogramming. As I saw in one of your examples, you want to await multiple tasks. If so, you don't need to use metaprogramming at all. Additionally, DotNext offers alternative ways to use data structures dynamically:
* [Type Classes](https://sakno.github.io/dotNext/features/concept.html). [Awaitable](https://sakno.github.io/dotNext/api/DotNext.Runtime.CompilerServices.Awaitable-3.html) is the example of built-in awaitable concept type
* [Dynamic Task Result](https://sakno.github.io/dotNext/features/core/index.html#dynamic-task-result) allows to obtain the result of async operation even if actual type `T` of `Task<T>` is not known.
* [Advanced Reflection](https://sakno.github.io/dotNext/features/reflection/fast.html) with close-to-zero overhead ([benchmarks](https://sakno.github.io/dotNext/benchmarks.html#fast-reflection)).

**Comment by Skyppid** [comment]
Thanks for the advice. Well Dynamic Task Result would be an option for sure. But I assume that a compiled method still performs better than (even close-to-zero overhead) reflection, doesn't it? And I mean it works now. I personally prefer expressions since you can compile them at runtime and use them without performance-loss at runtime.

But I'm certain that I'll look into other parts of DotNext as there's lots of useful stuff I can leverage in certain scenarios :)

**Comment by sakno** [comment]
Advanced Reflection in DotNext utilizes Expression Trees and dynamic compilation as well, but this fact completely hidden from the user. Close-to-zero means that the current implementation is magnitude faster than standard Reflection from .NET and even [FastMember](https://github.com/mgravell/fast-member) library. In some benchmarks, the overhead is not greater than tens of nanoseconds.
Dynamic Task Result also relies on dynamic code compilation using call site binder.

**Comment by Skyppid** [comment]
Okay good to know. Maybe I'll revamp this part of the code then since it's probably easier and more readable then. Thanks :)
