### ISSUE TITLE
DotNext.Threading.Synchronizer is not thread safe, is this intended?

### ISSUE THREAD

**Issue by Kikimora** [sakno/dotNext#22]
I noticed that Synchronizer uses internal state quite liberally and would fail in a multithreaded environment. Code like this 
```csharp
return node is null ? CompletedTask<bool, BooleanConst.True>.Task : node.Task.WaitAsync(timeout, token);
```
will fail with NullReferenceException if other thread calls `AsyncManualResetEvent.Set(false)`. With a small modification example code [here](https://sakno.github.io/dotNext/features/threading/event.html) would trigger this error.

**Comment by sakno** [comment]
Hi @Kikimora . Actually, access to internal state is protected by `[MethodImpl(MethodImplOptions.Synchronized)]` attribute applied to all critical methods of `Synchronizer` class.

**Comment by Kikimora** [comment]
Now it make sense, thanks for pointing this out. It is first time I see `[MethodImpl(MethodImplOptions.Synchronized)]` used somewhere, definitely rare construct.
