### ISSUE TITLE
Untyped async lambda expression?

### ISSUE THREAD

**Issue by adamjones1** [sakno/dotNext#23]
Hi, is there support here for an untyped async lambda expression (akin to `LambdaExpression` in the standard library)? I see there's `AsyncLambdaExpression<TDelegate>` but I don't know the input/return types at the time of constructing the expression in my use case. Thanks!

**Comment by sakno** [comment]
@adamjones1 , there is no support of untyped async lambdas at the moment. The main problem is the return type which can be represented by `ValueTask`, `Task`, `Task<T>` or `ValueTask<T>` (other types are not supported by Metaprogramming library). It's not possible to construct async state machine without this knowledge. Could you please provide more details about your use case?
