### ISSUE TITLE
Async suffix for Wait method

### ISSUE THREAD

**Issue by TechInterMezzo** [sakno/dotNext#4]
This is more like a question.
Shouldn't the Wait method of the [Synchronizer](https://sakno.github.io/dotNext/api/DotNext.Threading.Synchronizer.html) class have the Async suffix? I learnt somewhere that every async method or every method returning a task should have that suffix. Are there logical exceptions?

**Comment by sakno** [comment]
_Async_ suffix usually used in situations where your API surface contain pair of methods for synchronous and asynchronous calls in the same time. _System.IO.Stream_ is a good example.
You can find related discussion on [StackOverflow](https://stackoverflow.com/questions/15951774/does-the-use-of-the-async-suffix-in-a-method-name-depend-on-whether-the-async) with the comment from Stephen Toub which is applicable to my case:
> Of course, there are always exceptions to a guideline. The most notable one in the case of naming would be cases where an entire type’s raison d’etre is to provide async-focused functionality, in which case having Async on every method would be overkill, e.g. the methods on Task itself that produce other Tasks. 

[Synchronizer](https://sakno.github.io/dotNext/api/DotNext.Threading.Synchronizer.html) and its derived classes make sense in async scenarios only so _Async_ suffix is redundant.

**Comment by sakno** [comment]
Probably, _Async_ suffix is more intuitive for developers. I can change the name but in scheduled 2.x version. I can't change it in 1.x because of backward compatibility.
