### ISSUE TITLE
Possible problem with redirect logic

### ISSUE THREAD

**Issue by natilivni** [sakno/dotNext#44]
If my cluster is configured to have the following members:
localhost:1000, localhost:1001, localhost:1002

The following code will not redirect to the leader properly since the port that is used for the redirect is not the leader port:

```
internal Task Redirect(HttpContext context)
{
    if (context.Request.Path.StartsWithSegments(pathMatch, StringComparison.OrdinalIgnoreCase))
    {
        var leader = cluster.Leader;
        if (leader is null)
        {
            context.Response.StatusCode = StatusCodes.Status503ServiceUnavailable;
            return Task.CompletedTask;
        }
        else if (leader.IsRemote)
        {
            return redirection(context.Response, new UriBuilder(context.Request.GetEncodedUrl()) { Host = leader.Endpoint.Address.ToString(), Port = applicationPortHint ?? context.Connection.LocalPort }.Uri);
        }
    }

    return next(context);
}
```
should this not use something like the following?
```
new UriBuilder(context.Request.GetEncodedUrl()) { Host = leader.Endpoint.Address.ToString(), Port = leader.Endpoint.Port }.Uri)
```

**Comment by sakno** [comment]
The logic is correct. In embedded mode, Raft service endpoint shares the same port with main application. In hosted mode, Raft service endpoint uses separated port. Service endpoint is responsible for working with Raft RPC calls, which is black box to end user. API exposed via main endpoints by the application implementing high-level data access logic, such as data reads and writes, locks etc. Therefore, redirection works with application port.

**Comment by natilivni** [comment]
This will only work assuming all nodes share the same port and have different IPs. Something that will indeed be universally true in any deployed environment. In a local environment, however, it is legitimate to host nodes on the same IP with a different port for each node, in which case this logic fails since it ends up rerouting to itself.

**Comment by sakno** [comment]
When you deploying microservice, you assuming that it's configuration is identical for each hosting node except infrastructure. In case of Docker or Kubernetes it's true. Moreover, it's hard to write deployment scenario in Octopus or Ansible to have a different configuration for each instance of the same microservice. For local dev you still can use Kubernetes or Docker deployed locally or on virtual machine.

I don't see the reason to have some special support for loopback address because this configuration will not be relevant to any real production environment.

**Comment by sakno** [comment]
If you still want to use local host as testing env then just register additional loopback interfaces. It's easily can be done on Linux or FreeBSD. Check [this](https://askubuntu.com/questions/444124/how-to-add-a-loopback-interface) discussion as an example. Not sure about Windows, I'm not using it.

**Comment by sakno** [comment]
I checked it on Windows, you can register additional Loopback Adapters through Control Pane as described [here](https://docs.microsoft.com/en-us/troubleshoot/windows-server/networking/install-microsoft-loopback-adapter).

**Comment by sakno** [comment]
From my point view, your dev and test environment should be close to the production environment to eliminate potential infrastructure problems during deployment.
