### ISSUE TITLE
AsyncForEach

### ISSUE THREAD

**Issue by GerardSmit** [sakno/dotNext#45]
Currently it's possible to create a foreach-statement with `CodeGenerator.ForEach`, but it's not possible to create an async foreach-statement.

## Suggestion
Create a new method in `CodeGenerator` named `AsyncForEach` that does the same as `ForEach` but for `IAsyncEnumerable`.

## Example
**C#**
```csharp
IAsyncEnumerable<string> elements;

async foreach (var element in elements)
{
	// use element
}
```

**DotNext.Linq.Expressions**
```csharp
Expression elements;

CodeGenerator.AsyncForEach(elements, element =>
{
	// use element
});
```

**Comment by sakno** [comment]
The actual statement is `await foreach`, not `async foreach`. This statement is already supported, take a look at [this](https://sakno.github.io/dotNext/features/metaprogramming/loop.html#await-foreach-loop) doc.

**Comment by GerardSmit** [comment]
Oops, seems like it was a long day that I didn't notice this 🤦‍♂️. Thanks!
