### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by natilivni** [sakno/dotNext#53]
The documentation guide is missing at this link: https://sakno.github.io/dotNext/migration/2.html

**Comment by sakno** [comment]
Hi @natilivni ! I apologize for inconvenience, but latest version of DocFX crashes in attempt to generate API doc for .NET 5 target. Related issues:
* dotnet/docfx#7022
* dotnet/docfx#6866
* dotnet/docfx#6790

The current documentation is fully based on DocFX. Migration to another doc gen tool looks too expensive. But I'm trying to find the alternative. Probably, I'll use [fuget.org](https://www.fuget.org/packages/DotNext/3.0.0/lib/netstandard2.1/DotNext.dll/DotNext.Threading/AtomicEnum%601) as a replacement for API doc.

**Comment by sakno** [comment]
API doc has moved to FuGet Gallery. All links in articles are updated accordingly. Closing issue.
