### ISSUE TITLE
DotNext.Metaprogramming. Regression: worked in v 2.12.2, hangs in higher versions.

### ISSUE THREAD

**Issue by ycherkes** [sakno/dotNext#70]
public class Test
    {
        [Fact]
        public async Task AsyncLambdaDoesntHangInTryBlock()
        {
            Expression<Func<Task<string>>> exprThrowException = () => ThrowException();
            Expression<Func<Task<string>>> exprReprocess = () => Reprocess();

            var asyncTryCatchExpression = AsyncLambda<Func<Task<string>>>(
                (lambdaContext, result) =>
                {
                    Try(() =>
                        {

                            Assign(result, Expression.Invoke(exprThrowException).Await());
                            Return(result);
                        })
                        .Catch<Exception>(() =>
                        {
                            Assign(result, Expression.Invoke(exprReprocess).Await());
                            Return(result);
                        })
                        .End();
                });

            var asyncTryCatchFunc = asyncTryCatchExpression.Compile();
            var asyncTryCatchTask = asyncTryCatchFunc();

            var cancellationTokenSource = new CancellationTokenSource(TimeSpan.FromSeconds(5));
            await await Task.WhenAny(asyncTryCatchTask, Task.Delay(-1, cancellationTokenSource.Token));
        }

        private static async Task<string> ThrowException()
        {
            await Task.Delay(TimeSpan.FromSeconds(1));
            throw new Exception();
        }

        private static Task<string> Reprocess()
        {
            return Task.FromResult(string.Empty);
        }
    }

**Comment by sakno** [comment]
@ycherkes , patch has been added to `develop` branch

**Comment by ycherkes** [comment]
> @ycherkes , patch has been added to `develop` branch

Thank you. I can check it on my project code on Monday.

**Comment by ycherkes** [comment]
Hi @sakno, 
I've just checked the dev version in my project. 
Hangs are gone.
When do you plan to release it?

**Comment by sakno** [comment]
I hope this evening.

**Comment by ycherkes** [comment]
> I hope this evening.

I saw that version 3.2.0 was released. Thank you.
